name: segal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - apscheduler=3.6.3=py37hc8dfbb8_2
  - argon2-cffi=20.1.0=py37h8f50634_2
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_0
  - cffi=1.14.3=py37h00ebd2e_1
  - cftime=1.2.1=py37h161383b_1
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.2.1=py37hc72a4ac_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - double-conversion=3.1.5=he1b5a44_2
  - eigen=3.3.8=hc9558a2_0
  - entrypoints=0.3=py37hc8dfbb8_1002
  - expat=2.2.9=he1b5a44_2
  - fastcache=1.1.0=py37h8f50634_2
  - ffmpeg=4.3.1=h3215721_1
  - firefox=93.0=h9c3ff4c_0
  - flask=1.1.2=pyh9f0ad1d_0
  - freetype=2.10.4=h7ca028e_0
  - geckodriver=0.29.1=h3146498_0
  - gl2ps=1.4.2=he06d7ca_0
  - glew=2.1.0=he1b5a44_0
  - gmp=6.2.0=h58526e2_4
  - gmpy2=2.1.0b1=py37h0067bfd_1
  - gnutls=3.6.13=h79a8f9a_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h54c07f9_1110
  - icu=67.1=he1b5a44_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py37hc6149b9_1
  - ipython=7.19.0=py37h888b3d9_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=1.1.0=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h36c2ea0_0
  - jsoncpp=1.8.4=hc9558a2_1002
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py37hc928c03_0
  - krb5=1.17.1=hfafb76e_3
  - lame=3.100=h14c3975_1001
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.35=h769bd43_9
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - libnetcdf=4.7.4=nompi_hefab0ff_106
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libogg=1.3.2=h516909a_1002
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtheora=1.1.1=h516909a_1004
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.7=he1b5a44_0
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - llvm-openmp=11.0.0=hfc4b9b4_1
  - loguru=0.5.3=py37hc8dfbb8_2
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=1.1.1=py37hb5d75c8_2
  - matplotlib-base=3.2.2=py37h1d35a4c_1
  - mistune=0.8.4=py37h8f50634_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h8f50634_2
  - mkl_fft=1.2.0=py37h161383b_1
  - mkl_random=1.2.0=py37h9fdb41a_1
  - monty=4.0.2=pyh9f0ad1d_0
  - mpc=1.1.0=h04dde30_1009
  - mpfr=4.0.2=he80fd80_1
  - nb_conda_kernels=2.2.2=py37_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37hc8dfbb8_2
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h58526e2_3
  - nest-asyncio=1.4.2=pyhd8ed1ab_0
  - netcdf4=1.5.4=nompi_py37hcbfd489_103
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.5=py_0
  - ninja=1.10.1=hfc4b9b4_2
  - notebook=6.1.4=py37hc8dfbb8_1
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1l=h7f98852_0
  - packaging=20.4=pyh9f0ad1d_0
  - palettable=3.3.0=py_0
  - pandoc=2.11.0.4=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.0=py_1
  - patsy=0.5.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py37h718be6c_0
  - pip=20.2.4=py_0
  - plotly=4.12.0=pyh9f0ad1d_0
  - proj=7.1.1=h966b41f_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pugixml=1.10=he1b5a44_1
  - pybtex=0.23.0=py37hc8dfbb8_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.2=py_0
  - pymatgen=2020.8.3=py37h99015e2_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h8f50634_1
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.8=h6f2ec95_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.5.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.4=pyhd8ed1ab_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - pyzmq=19.0.2=py37hac76be4_2
  - readline=8.0=he28a2e2_2
  - retrying=1.3.3=py_2
  - ruamel.yaml=0.16.12=py37h8f50634_1
  - ruamel.yaml.clib=0.2.2=py37h8f50634_1
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.5.2=py37h0b6359f_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37he5f6b98_2
  - six=1.15.0=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - sqlite=3.33.0=h4cf870e_1
  - statsmodels=0.12.1=py37ha21ca33_1
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tbb=2020.2=hc9558a2_0
  - tbb-devel=2020.2=hc9558a2_0
  - terminado=0.9.1=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_1
  - torchvision=0.6.0=py37_cu101
  - tornado=6.1=py37h4abf009_0
  - tqdm=4.51.0=pyh9f0ad1d_0
  - traitlets=5.0.5=py_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - utfcpp=3.1.2=0
  - vtk=9.0.1=no_osmesa_py37h8af0cc8_102
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - absl-py==0.14.1
    - alphashape==1.3.0
    - ase==3.19.1
    - astunparse==1.6.3
    - bokeh==2.3.3
    - cached-property==1.5.2
    - cachetools==4.2.4
    - clang==5.0
    - clease==0.9.11
    - click-log==0.3.2
    - click-plugins==1.1.1
    - cligj==0.7.1
    - clusterx==1.0.0.dev8
    - colorama==0.4.4
    - descartes==1.1.0
    - docutils==0.16
    - et-xmlfile==1.1.0
    - fiona==1.8.19
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.4.0
    - geopandas==0.9.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - grpcio==1.41.0
    - h11==0.12.0
    - h5py==3.1.0
    - idna==2.8
    - imageio==2.11.0
    - ipywidgets==7.5.1
    - isodate==0.6.0
    - jupyterthemes==0.20.0
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kivy==1.11.1
    - kivy-garden==0.1.4
    - kivy-garden-graph==0.4.1.dev0
    - lesscpy==0.13.0
    - llvmlite==0.34.0
    - markdown==3.3.4
    - matplotlib==3.1.3
    - megnet==1.2.9
    - mendeleev==0.6.1
    - mpmath==1.1.0
    - munch==2.5.0
    - nglview==2.7.5
    - numba==0.51.2
    - numpy==1.17.4
    - oauthlib==3.1.1
    - openpyxl==3.0.9
    - opt-einsum==3.3.0
    - outcome==1.1.0
    - pandas==1.3.0
    - pickle5==0.0.11
    - plac==1.2.0
    - plotly-express==0.4.1
    - pluggy==0.13.1
    - ply==3.11
    - protobuf==3.18.1
    - py==1.8.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfiglet==0.8.post1
    - pyproj==3.0.1
    - pytest==5.4.3
    - pywavelets==1.2.0
    - rdflib==5.0.0
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - rtree==0.9.7
    - schnetpack==1.0.0
    - scikit-image==0.18.3
    - seaborn==0.11.1
    - selenium==4.0.0
    - shapely==1.7.1
    - sigopt==5.3.1
    - sklearn==0.0
    - sniffio==1.2.0
    - sortedcontainers==2.4.0
    - spglib==1.15.1
    - sqlalchemy==1.3.23
    - sympy==1.6
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - tensorflow==2.6.0
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - tifffile==2021.11.2
    - torch==1.9.1
    - torch-cluster==1.5.8
    - torch-geometric==1.6.1
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - torchdiffeq==0.2.2
    - trimesh==3.9.12
    - trio==0.19.0
    - trio-websocket==0.9.2
    - typing-extensions==3.7.4.3
    - urllib3==1.25.7
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - wsproto==1.0.0
prefix: /home/james/miniconda3/envs/james_mlmat
